version: "2"
services:
  main_app:
    image: ${DOCKER_USERNAME}/${PROJECT_NAME}:${RJM_VERSION}
    environment:
      APIAPP_APIURL: http://${PROJECT_NAME}:80/api
      APIAPP_APIDOCSURL: http://${PROJECT_NAME}:80/apidocs
      APIAPP_FRONTENDURL: http://${PROJECT_NAME}:80/frontend
      APIAPP_MASTERPASSWORDFORPASSHASH: ABCCC
      APIAPP_DEFAULTHOMEADMINUSERNAME: admin
      APIAPP_DEFAULTHOMEADMINPASSWORD: admin
      APIAPP_JWTSECRET: someDummy3245SecretForTesting

  main_apptest:
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGENAME}test:develop
    command: /run_tests_with_wait.sh
    environment:
      EXPECTED_CONTAINER_VERSION: ${RJM_VERSION}
      TESTPARAM_ENDPOINTURL: http://main_app:8095
      TESTPARAM_THROUGHKONG: FALSE
      APIAPP_DEFAULTHOMEADMINUSERNAME: admin
      APIAPP_DEFAULTHOMEADMINPASSWORD: admin
