name: build_test_and_deploy

on:
  push:
    tags:
      - '*'

jobs:
  build_test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # === prepare stage ===
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Load repo vars
        run: |
          source ./_repo_vars.sh
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV

      # === build stage ===
      - name: Read Docker credentials from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: true
          secrets: |
            kv/data/robert_accounts/dockerhub/personal_access_tokens/${{ env.PROJECT_NAME }}_deployment username | DOCKER_USERNAME ;
            kv/data/robert_accounts/dockerhub/personal_access_tokens/${{ env.PROJECT_NAME }}_deployment password | DOCKER_PASSWORD ;
            kv/data/memset/deployment/ssh SSH_KEY | SSH_KEY ;
            kv/data/memset/deployment/ssh SPLIT_CHAR | SPLIT_CHAR ;
            kv/data/memset/deployment/ssh SSH_PORT | SSH_PORT ;
            kv/data/memset/deployment/ssh SSH_HOST | SSH_HOST ;
            kv/data/memset/deployment/ssh SSH_USER | SSH_USER

      - name: Unit tests
        run: |
          source ./_repo_vars.sh && \
          echo "Running uint tests for ${PROJECT_NAME}" && \
          docker run --rm -v "$PWD/services:/opt/services" -w /opt/services \
            ${RJM_PYTHON_TEST_IMAGE} \
            sh -c "pip3 install --no-cache-dir -r ./src/requirements.txt && \
                   pip3 install --no-cache-dir -r ./testContainer/requirements.txt && \
                   SKIPSQLALCHEMYTESTS=Y python3 -m pytest ./test"

      - name: Build frontend
        run: |
          source ./_repo_vars.sh && \
          docker run --rm -v "$PWD:/opt/work" -w /opt/work \
            ${QUASARBUILDIMAGE} \
            -c "build_quasar_app ./frontend ${QUASARBUILDMODE} ${RJM_VERSION}"

      - name: Build main image
        run: |
          source ./_repo_vars.sh && \
          docker build --build-arg PROJECT_NAME="${PROJECT_NAME}" --build-arg QUASARBUILDMODE="${QUASARBUILDMODE}" -t ${DOCKER_USERNAME}/${PROJECT_NAME}:${RJM_VERSION} .

      - name: Build test image
        run: |
          source ./_repo_vars.sh && \
          docker build -t ${DOCKER_USERNAME}/${PROJECT_NAME}test:develop \
            -f services/testContainer/Dockerfile services/testContainer

      - name: Container level tests
        run: |
          source ./_repo_vars.sh && \
          docker compose -f .github/compose-test.yml up --abort-on-container-exit --exit-code-from main_apptest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Push images to dockehub
        run: |
          source ./_repo_vars.sh && \
          docker push ${DOCKER_USERNAME}/${PROJECT_NAME}:${RJM_VERSION}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          # Convert the split-char SSH key back into a real multiline key
          echo "${SSH_KEY}" | sed "s/${SPLIT_CHAR}/\n/g" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Add host to known_hosts
          ssh-keyscan -p "${SSH_PORT}" "${SSH_HOST}" >> ~/.ssh/known_hosts

      # Artifacts created now deploy to server
      - name: Deploy Docker Service to Swarm
        run: |
          source ./_repo_vars.sh && \
          ssh -p "${SSH_PORT}" \
            -i ~/.ssh/id_rsa \
            "${SSH_USER}@${SSH_HOST}" \
            bash -s << EOF

          docker service create --name "${RJM_DOCKER_SERVICE_NAME}" \
            --network main_net \
            --secret ${PROJECT_NAME}_vault_roleid \
            --secret ${PROJECT_NAME}_vault_secretid \
            -e APIAPP_VAULT_URL=https://vault.metcarob.com/ \
            -e APIAPP_VAULT_ROLE_IDFILE=/run/secrets/${PROJECT_NAME}_vault_roleid \
            -e APIAPP_VAULT_SECRET_IDFILE=/run/secrets/${PROJECT_NAME}_vault_secretid \
            -e APIAPP_JWTSECRETVAULT=memset/deployment/commonsecrets:APIAPP_JWTSECRET \
            -e APIAPP_DEFAULTHOMEADMINUSERNAME=admin \
            -e APIAPP_APIURL=https://api.metcarob.com/api \
            -e APIAPP_APIDOCSURL=https://api.metcarob.com/${PROJECT_NAME}/v${RJM_MAJOR_VERSION}/public/web/apidocs \
            -e APIAPP_FRONTENDURL=https://api.metcarob.com/${PROJECT_NAME}/v${RJM_MAJOR_VERSION}/public/web/frontend \
            -e APIAPP_DEFAULTMASTERTENANTJWTCOLLECTIONALLOWEDORIGINFIELD="https://api.metcarob.com,https://localhost,http://localhost" \
            --constraint 'node.labels.legacy == true' \
            "${DOCKER_USERNAME}/${PROJECT_NAME}:${RJM_VERSION}"

          EOF

      #endpoints are secured the first time they are created. This will add the plugins only if they are not there
      - name: Configure kong for new service
        run: |
          source ./_repo_vars.sh && \
          docker run --rm -i --volume=${HOME}/.ssh/id_rsa:/root/.ssh/id_rdocker:ro --volume=$(pwd):/working -e SSH_PORT=${SSH_PORT} -w /working --entrypoint transferDirectory ${RJM_DOCKERWSCALLER_IMAGE} ${SSH_USER}@${SSH_HOST} ./terraform/ ${MEMSET_CLOUD_ROOT}/data_to_backup/terraform/executions/${PROJECT_NAME} && \
          ssh -p "${SSH_PORT}" \
            -i ~/.ssh/id_rsa \
            "${SSH_USER}@${SSH_HOST}" \
            bash -s << EOF
              ${MEMSET_CLOUD_ROOT}/scripts/update_terraform_deployment.sh  setup_test ${MEMSET_CLOUD_ROOT} ${PROJECT_NAME} ${RJM_VERSION}
              ${MEMSET_CLOUD_ROOT}/scripts/execute_terraform.sh ${MEMSET_CLOUD_ROOT} ${PROJECT_NAME}
          EOF

      - name: Test the newly deployed container using test endpoint
        run: |
          source ./_repo_vars.sh && \
          sleep 5 && \
          docker run --rm \
            -e HTTPORIGIN_TO_TEST=https://api.metcarob.com \
            -e APIAPP_DEFAULTHOMEADMINUSERNAME=codefresh_test_user \
            -e APIAPP_DEFAULTHOMEADMINPASSWORD=${SAASCODEFRESHTESTUSERPASSWORD} \
            -e TESTPARAM_ENDPOINTURL=https://api.metcarob.com/${PROJECT_NAME}/test/v${RJM_MAJOR_VERSION} \
            -e TESTPARAM_THROUGHKONG="TRUE" \
            -e TESTPARAM_EXPECTED_CONTAINER_VERSION="${RJM_VERSION}" \
            ${DOCKER_USERNAME}/${PROJECT_NAME}test:develop \
            python3 -m pytest /test

      - name: Configure kong upstream for prod service
        run: |
          source ./_repo_vars.sh && \
          docker run --rm -i --volume=${HOME}/.ssh/id_rsa:/root/.ssh/id_rdocker:ro --volume=$(pwd):/working -e SSH_PORT=${SSH_PORT} -w /working --entrypoint transferDirectory ${RJM_DOCKERWSCALLER_IMAGE} ${SSH_USER}@${SSH_HOST} ./terraform/ ${MEMSET_CLOUD_ROOT}/data_to_backup/terraform/executions/${PROJECT_NAME} && \
          ssh -p "${SSH_PORT}" \
            -i ~/.ssh/id_rsa \
            "${SSH_USER}@${SSH_HOST}" \
            bash -s << EOF
              ${MEMSET_CLOUD_ROOT}/scripts/update_terraform_deployment.sh deploy ${MEMSET_CLOUD_ROOT} ${PROJECT_NAME} ${RJM_VERSION}
              ${MEMSET_CLOUD_ROOT}/scripts/execute_terraform.sh ${MEMSET_CLOUD_ROOT} ${PROJECT_NAME}
          EOF

      # no longer approve cleanup old version - just go straight ahead and cleanup
      - name: Clean up old versions
        run: |
          source ./_repo_vars.sh && \
          ssh -p "${SSH_PORT}" \
            -i ~/.ssh/id_rsa \
            "${SSH_USER}@${SSH_HOST}" \
            bash -s << EOF
              docker run --rm -i --network main_net --volume=/var/run:/var/run --entrypoint docker_service_remove_non_live \
                ${RJM_DOCKERWSCALLER_IMAGE} \
                ${PROJECT_NAME} \
                ${RJM_VERSION} \
                ${DOCKER_USERNAME}/

          EOF
